# Generated by Django 5.0.1 on 2024-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='users_count',
            field=models.IntegerField(default=0, verbose_name='Общее количество участников опроса'),
        ),
    ]
